<?php
use Lolphp\Entity\Summoner as SummonerEntity;

/**
 * @var SummonerEntity $summoner
 */
$summoner       = $this->view->summoner;

?>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-1">
            <img
                src="http://lkimg.zamimg.com/shared/riot/images/profile_icons/profileIcon<?= $summoner->getProfileIconId() ?>.jpg"
                width="84px"
                height="84px"
            />
        </div>
        <div class="col-md-4">
            <h1>
                <?= $summoner->getName() ?>
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-offset-1 col-md-4">
            ID: <?= $summoner->getId() ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-6">
        <table class="table table-bordered">
            <tr>
                <th>Summoner Level</th>
                <td><?= $summoner->getSummonerLevel() ?></td>
            </tr>
        </table>
    </div>
    <div class="col-sm-6">
        <table class="table table-bordered">
            <tr>
                <th>Last Updated</th>
                <td><?= $summoner->getRevisionDate()->format('m-d-Y H:i:s A') ?></td>
            </tr>
        </table>
    </div>
</div>